# Generated by Django 3.2.9 on 2021-11-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convertexcel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='output',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='excel_file',
            field=models.FileField(upload_to='static/excel/'),
        ),
    ]
