# Generated by Django 3.2.9 on 2021-11-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convertexcel', '0002_auto_20211116_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='output',
            field=models.FileField(blank=True, upload_to='static/excel_output/'),
        ),
    ]
